### ISSUE TITLE
run.py error

### ISSUE THREAD

**Issue by rullskidan** [plaperdr/blink-docker#10]
I have some problems when I try to run blink-docker on ubuntu. I
follow this instruction: 

git clone https://github.com/plaperdr/blink-docker.git
cd blink-docker/
python3 downloadFromHub.py
python3 run.py

Everything is fine until I run "python3 run.py" then nothing happends
and I receive this: 

home@home-VirtualBox:~/blink-docker$ python3 run.py
Traceback (most recent call last):
  File "run.py", line 208, in <module>
    main()
  File "run.py", line 143, in main
    checkInstallation()
  File "run.py", line 38, in checkInstallation
    generateLibrairies()
  File "run.py", line 66, in generateLibrairies
    ubuKernel =
    re.search("linux-image-(.*?)\">",str(ubuSource)).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I am running ubuntu 16.04 and I have tried to do the complete
installation again but the results are the same.

Are there some problems with the installation or is it just me that have
these issues?

Could you check it? What can I do to fix it?

**Comment by plaperdr** [comment]
Thanks for your interest in Blink! Your log helped me pinpoint the problem. It should now be fixed by commit 42113f2f00f1bbf460921bad4141b1e5b576fc66. Can you check if it works on your side?

**Comment by rullskidan** [comment]
Yes it helps but now I receive another error:

LD Preload libraries generated
installComplete file written
Installation verified
Image blinkubu chosen
Europe/Belgrade timezone chosen
Launching Blink browsing environment
Error response from daemon: No such container: torproxy
Error: failed to start containers: torproxy
docker: Error response from daemon: No such container: torproxy.
Error response from daemon: No such container: torproxy
End of script

What should I do now?

**Comment by plaperdr** [comment]
Did you run the "downloadFromHub.py" python script before the "run.py" one? Normally, it installs the "torproxy" container that is used by Blink

**Comment by rullskidan** [comment]
Yes I have run that script before run.py but I remember that it was displaying red text end some errors when it was downloading the tor parts when I watched the log in terminal after starting downloadFromHub.py

Is it possible to run blink without tor and setting your own proxy?

Maybe the "jess/tor-proxy", is not working as supposed? Should I just replace it with some other torproxy from docker hub?

**Comment by rullskidan** [comment]
I mean in regards to tor container
