### ISSUE TITLE
problem on aws

### ISSUE THREAD

**Issue by X-777** [plaperdr/blink-docker#14]
excuse me，Why does my blink build on aws always give an error when executing python3 run.py

Error: no DISPLAY environment variable specified
Error: GDK_BACKEND does not match available displays
Data import
Using PPAPI flash.
[298:298:0517/084640.139153:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Data export
Traceback (most recent call last):
  File "/home/blink/mainContainer.py", line 209, in <module>
    main()
  File "/home/blink/mainContainer.py", line 188, in main
    encryption,refresh = browser.exportData()
  File "/home/blink/chrome.py", line 162, in exportData
    self.exportOpenTabs()
  File "/home/blink/chrome.py", line 107, in exportOpenTabs
    self.jsonExportData["refresh"] = data["refresh"]
KeyError: 'refresh'

**Comment by plaperdr** [comment]
Hi! Thanks for your interest in Blink!
I have never tried it on AWS but looking at the error, Blink complains because it runs in an environment with a display and there is not one in there apparently. You could try maybe running a VNC server and have Blink connect to it. I haven't developed a headless version of Blink for crawling.

**Comment by X-777** [comment]
Can you provide a development environment, such as the mirror of vm?
