### ISSUE TITLE
python3 run.py error

### ISSUE THREAD

**Issue by czahoi** [plaperdr/blink-docker#15]
root@kali:~/blink-docker# python3 run.py 
Traceback (most recent call last):
  File "run.py", line 208, in <module>
    main()
  File "run.py", line 142, in main
    checkInstallation()
  File "run.py", line 38, in checkInstallation
    generateLibrairies()
  File "run.py", line 54, in generateLibrairies
    fedKernel = re.search("kernel-(.{1,20}"+fedoraName+")((?!testing).)*?stable",str(fedSource)).group(1)+".x86_64"
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by czahoi** [comment]
tried in debian,kali,ubuntu18.02. same error

**Comment by czahoi** [comment]
Actually, i`d like to know about your deploy environment. or any deployed vm mirrors.

**Comment by Mohsentrade741** [comment]
Hi
Is this project still active? Have you fould the above problem solution?
